# TODO: Make this replayable without overwriting changes

- name: Clone LazyVim
  shell: "git clone https://github.com/LazyVim/starter ~/.config/nvim"
  ignore_errors: yes

- name: Rm the .git directory
  shell: "rm -rf ~/.config/nvim/.git"
  ignore_errors: yes

- name: Copy our base configuration to the share directory
  copy:
    src: "./lazy.lua"
    dest: "~/.config/nvim/lua/config/lazy.lua"

- debug:
    msg: "LazyVim installed. You have been provided with my basic configuration for Neovim. You can enable further extras by using the :LazyExtras command in Neovim."
