# Setup a new service
# - service_user: the service user

- name: Debug
  debug:
    msg: 
     - "Create Service User"
     - "{{ service_user }}"

- name: Check if the service user exists
  become: yes
  shell: "id {{ service_user }}"
  register: user_check
  ignore_errors: yes

- name: Create the service user
  become: yes
  user:
    name: "{{ service_user }}"
    shell: /bin/bash
    state: present
  when: user_check.rc != 0
# # TODO: remove
# - name: Make sure the service user has a home directory
#   become: yes
#   file:
#     path: /home/{{ service_user }}
#     state: directory
#     owner: "{{ service_user }}"
#     group: "{{ service_user }}"
#   when: user_check.rc != 0

- name: Get the admin user's ssh pub key
  become: yes
  shell: "cat /etc/ssh/authorized/admin/authorized_keys"
  register: admin_ssh_pub_key
  when: user_check.rc != 0
- name: Make sure the service user has a .ssh directory
  become: yes
  file:
    path: "/etc/ssh/authorized/{{ service_user }}/authorized"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0700'
  when: user_check.rc != 0
- name: Make sure the service user has an authorized_keys file
  become: yes
  file:
    path: "/etc/ssh/authorized/{{ service_user }}/authorized_keys"
    state: touch
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0600'
  when: user_check.rc != 0
- name: Add the admin's ssh pub key
  become: yes
  lineinfile:
    path: "/etc/ssh/authorized/{{ service_user }}/authorized_keys"
    line: "{{ admin_ssh_pub_key.stdout }}"
    state: present
    regexp: "^{{ admin_ssh_pub_key.stdout | regex_escape() }}"
  ignore_errors: yes
  when: user_check.rc != 0