- name: Debug
  debug:
    msg:
      - "Creating Nginx Basic Auth for user {{ basic_auth_user }}"

- name: Create the /etc/nginx/.htpasswd_<basic_auth_user> file
  become: yes
  file:
    path: "/etc/nginx/.htpasswd_{{ basic_auth_user }}"
    state: touch
    owner: www-data
    group: www-data
    mode: '0600'

# TODO: this is very, very crude. There should be a better way to manage secrets. For now it will do.
- name: Generate a random password openssl
  set_fact:
    password: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters,digits') }}"
# TODO: this assumes the service has a user + home directory. This is not always the case.
- name: Save the user's password to a file on the instance
  become: yes
  copy:
    content: "{{ password }}"
    dest: /home/{{ basic_auth_user }}/.basic_auth.password
    mode: '0600'
    owner: "{{ basic_auth_user }}"
    group: "{{ basic_auth_user }}"

- name: Add our (single entry) user to the .htpasswd_<basic_auth_user> file
  become: yes
  shell: "echo -n '{{ basic_auth_user }}:' > /etc/nginx/.htpasswd_{{ basic_auth_user }} && openssl passwd -apr1 {{ password }} >> /etc/nginx/.htpasswd_{{ basic_auth_user }}"