- name: Debug
  debug:
    msg:
      - "Creating SSL Cert for {{ target_domain }}"
      - "Admin Email: {{ email }}"

- name: Generate Let's Encrypt certificate
  become: yes
  shell: certbot --nginx -d {{ target_domain }} --non-interactive --agree-tos -m {{ email }}

# 0 12 * * * /usr/bin/certbot renew --quiet
- name: Add a cronn job to auto renew certificates if one doesn't already exist
  become: yes
  cron:
    name: renew_certs
    minute: 0
    hour: 12
    job: /user/bin/certbot renew --quiet