# Initialize our Nginx Configuration
# Configuraiton:
# - email: email to associate with the certificate
# - domain: your domain (this should already have an A record pointing to your domain)
# TODO: configure static assets based on domain perhaps. For now I only care about a single domain.

- name: Debug
  debug:
    msg:
     - "Init Nginx Configuration"
     - "{{ email }}"
     - "{{ domain }}"

- name: Remove default Nginx configuration
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Copy static site files assets
  become: yes
  template:
    src: ./static/index.html.j2
    dest: "/var/www/html/{{ domain }}/index.html"
    owner:  www-data
    group: www-data
    mode: 0643

# Setup root domain

- name: Setup server block
  become: yes
  template:
    src: ./config.j2
    dest: "/etc/nginx/sites-available/{{ domain }}"

- name: Enable the server block
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ domain }}"
    dest: "/etc/nginx/sites-enabled/{{ domain }}"
    state: link

- name: Setup domain SSL certificate
  import_tasks: ./ssl.tasks.yml
  vars:
    target_domain: "{{ domain }}"
    email: "{{ email }}"

# Setup ipfs sub domain

- name: Setup server block
  become: yes
  template:
    src: ./ipfs.config.j2
    dest: "/etc/nginx/sites-available/ipfs.{{ domain }}"

- name: Enable the server block
  become: yes
  file:
    src: "/etc/nginx/sites-available/ipfs.{{ domain }}"
    dest: "/etc/nginx/sites-enabled/ipfs.{{ domain }}"
    state: link

- name: Setup domain SSL certificate
  import_tasks: ./ssl.tasks.yml
  vars:
    target_domain: "ipfs.{{ domain }}"
    email: "{{ email }}"



- name: Restart Nginx
  become: yes
  service:
    name: nginx
    state: restarted