# Install required system dependencies for runnning all services
- hosts: all
  name: Install all dependencies on the host
  tasks:
    - name: Update Apt
      become: yes
      apt:
        name: "*"
        state: latest
        force_apt_get: true
    - name: Install Dependencies
      become: yes
      apt:
        name: "{{ item }}"
        state: present
        force_apt_get: true
      # TODO: can i scope these to specific groups?
      # register packages you want available to all users here
      with_items:
        - gcc
        - git
        - aria2
        - nginx
        - certbot
        - python3-certbot-nginx
        - openssl
        - apache2-utils
        - python3
        - python3-pip