# Setup the host to run web services over HTTPS
# email: email to publish as admin
# domain: root domain to associate with our services
- hosts: all
  name: Run Ipfs
  tasks:
    - name: Start the ipfs service
      import_tasks: ./ipfs/tasks.yml