# Setup the host to run web services over HTTPS
# email: email to publish as admin
# domain: root domain to associate with our services
- hosts: all
  name: Init our services on the host
  tasks:
    - name: Initialize Nginx
      import_tasks: ./nginx/tasks.yml
      vars:
        email: "{{ email }}"
        domain: "{{ domain }}"
        key_path: "/etc/nginx/ssl/{{ domain }}.key"
        cert_path: "/etc/nginx/ssl/{{ domain }}.crt"