# Start Ipfs on the host

- name: Check if the ipfs user exists
  become: yes
  shell: "id ipfs"
  register: ipfs_user_check
  ignore_errors: yes

- name: Create the ipfs service user
  import_tasks: ../utils/create_service.tasks.yml
  vars:
    service_user: ipfs
  when: ipfs_user_check.rc != 0

- name: Check if the /home/ipfs/.ipfs directory exists
  become: yes
  stat: 
    path: /home/ipfs/.ipfs
  register: ipfs_dir_stat

# We'll just take the existence of the .ipfs directory as a sign that the ipfs user has been initialized
- name: Install ipfs and create the ipfs user
  import_tasks: ./install.tasks.yml
  when: ipfs_dir_stat.stat.exists == False

- name: Start the ipfs service
  become: yes
  systemd:
    name: ipfs
    enabled: yes
    state: restarted